title:             Joalisson Andrade - Blog 
email:             joalisson.as@gmail.com
description:       A Blog about Full-stack developer course
author:            Joalisson Andrade
baseurl:           "/joalisson.dev"
url:               "http://joalisson.dev"

# Social Profiles
twitter_username:  joalisson_
github_username:   joalisson
facebook_username: joalisson.andrade

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
